In [49]:
import pandas as pd
import numpy as np
import os

In [50]:
data = pd.read_csv("C:/Users/juhis/Downloads/us_state_vaccinations.csv")

In [51]:
data.head()

,date,location,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used,total_boosters,total_boosters_per_hundred
0,2021-01-12,Alabama,78134.00,377025.00,70861.00,0.15,1.59,7270.00,1.45,7.69,NaN,NaN,NaN,0.21,NaN,NaN
1,2021-01-13,Alabama,84040.00,378975.00,74792.00,0.19,1.71,9245.00,1.53,7.73,5906.00,5906.00,1205.00,0.22,NaN,NaN
2,2021-01-14,Alabama,92300.00,435350.00,80480.00,NaN,1.88,NaN,1.64,8.88,8260.00,7083.00,1445.00,0.21,NaN,NaN
3,2021-01-15,Alabama,100567.00,444650.00,86956.00,0.28,2.05,13488.00,1.77,9.07,8267.00,7478.00,1525.00,0.23,NaN,NaN
4,2021-01-16,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7498.00,1529.00,NaN,NaN,NaN

In [52]:
data.dropna()

,date,location,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used,total_boosters,total_boosters_per_hundred
263,2021-10-02,Alabama,4544355.00,6738280.00,2586950.00,42.73,92.68,2094920.00,52.76,137.43,9583.00,10431.00,2127.00,0.67,2985.00,0.06
264,2021-10-03,Alabama,4565230.00,6736650.00,2592096.00,42.89,93.11,2103203.00,52.87,137.39,20875.00,11389.00,2323.00,0.68,10683.00,0.22
265,2021-10-04,Alabama,4579477.00,6736230.00,2595947.00,43.02,93.40,2109349.00,52.94,137.38,14247.00,12178.00,2484.00,0.68,14974.00,0.31
266,2021-10-05,Alabama,4584378.00,6742810.00,2597448.00,43.07,93.50,2111925.00,52.97,137.52,4901.00,10470.00,2135.00,0.68,15821.00,0.32
267,2021-10-06,Alabama,4594736.00,6757960.00,2600070.00,43.15,93.71,2115732.00,53.03,137.83,10358.00,11500.00,2345.00,0.68,19856.00,0.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52090,2022-06-12,Wyoming,758185.00,1014285.00,338217.00,51.23,131.00,296500.00,58.44,175.25,45.00,325.00,562.00,0.75,150227.00,25.96
52091,2022-06-13,Wyoming,758188.00,1014285.00,338220.00,51.23,131.00,296500.00,58.44,175.25,3.00,325.00,562.00,0.75,150227.00,25.96
52092,2022-06-14,Wyoming,758784.00,1015885.00,338314.00,51.24,131.11,296557.00,58.46,175.53,596.00,307.00,530.00,0.75,150679.00,26.03
52093,2022-06-15,Wyoming,759047.00,1015985.00,338384.00,51.25,131.15,296603.00,58.47,175.55,263.00,307.00,530.00,0.75,150830.00,26.06
52094,2022-06-16,Wyoming,759520.00,1016985.00,338492.00,51.26,131.23,296656.00,58.49,175.72,473.00,313.00,541.00,0.75,151146.00,26.12

In [53]:
data_df = data[['date','location','total_vaccinations','total_vaccinations_per_hundred','total_distributed',
                'distributed_per_hundred','people_vaccinated', 'people_vaccinated_per_hundred','people_fully_vaccinated',
                'people_fully_vaccinated_per_hundred','daily_vaccinations','daily_vaccinations_per_million',
                'total_boosters','total_boosters_per_hundred']].dropna()
data_df

,date,location,total_vaccinations,total_vaccinations_per_hundred,total_distributed,distributed_per_hundred,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,daily_vaccinations_per_million,total_boosters,total_boosters_per_hundred
263,2021-10-02,Alabama,4544355.00,92.68,6738280.00,137.43,2586950.00,52.76,2094920.00,42.73,10431.00,2127.00,2985.00,0.06
264,2021-10-03,Alabama,4565230.00,93.11,6736650.00,137.39,2592096.00,52.87,2103203.00,42.89,11389.00,2323.00,10683.00,0.22
265,2021-10-04,Alabama,4579477.00,93.40,6736230.00,137.38,2595947.00,52.94,2109349.00,43.02,12178.00,2484.00,14974.00,0.31
266,2021-10-05,Alabama,4584378.00,93.50,6742810.00,137.52,2597448.00,52.97,2111925.00,43.07,10470.00,2135.00,15821.00,0.32
267,2021-10-06,Alabama,4594736.00,93.71,6757960.00,137.83,2600070.00,53.03,2115732.00,43.15,11500.00,2345.00,19856.00,0.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52359,2023-03-08,Wyoming,850076.00,146.88,1264795.00,218.54,352806.00,60.96,307019.00,53.05,67.00,116.00,217238.00,37.54
52366,2023-03-15,Wyoming,850626.00,146.97,1267395.00,218.98,352934.00,60.98,307130.00,53.07,79.00,136.00,217549.00,37.59
52373,2023-03-22,Wyoming,851096.00,147.06,1269455.00,219.34,353073.00,61.01,307218.00,53.08,67.00,116.00,217792.00,37.63
52380,2023-03-29,Wyoming,851551.00,147.13,1272055.00,219.79,353200.00,61.03,307293.00,53.10,65.00,112.00,218045.00,37.67
52387,2023-04-05,Wyoming,851602.00,147.14,1273165.00,219.98,353233.00,61.03,307311.00,53.10,7.00,12.00,218045.00,37.67

In [54]:
data_df.head()

,date,location,total_vaccinations,total_vaccinations_per_hundred,total_distributed,distributed_per_hundred,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,daily_vaccinations_per_million,total_boosters,total_boosters_per_hundred
263,2021-10-02,Alabama,4544355.00,92.68,6738280.00,137.43,2586950.00,52.76,2094920.00,42.73,10431.00,2127.00,2985.00,0.06
264,2021-10-03,Alabama,4565230.00,93.11,6736650.00,137.39,2592096.00,52.87,2103203.00,42.89,11389.00,2323.00,10683.00,0.22
265,2021-10-04,Alabama,4579477.00,93.40,6736230.00,137.38,2595947.00,52.94,2109349.00,43.02,12178.00,2484.00,14974.00,0.31
266,2021-10-05,Alabama,4584378.00,93.50,6742810.00,137.52,2597448.00,52.97,2111925.00,43.07,10470.00,2135.00,15821.00,0.32
267,2021-10-06,Alabama,4594736.00,93.71,6757960.00,137.83,2600070.00,53.03,2115732.00,43.15,11500.00,2345.00,19856.00,0.40

In [55]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16970 entries, 263 to 52387
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   date                                 16970 non-null  object
 1   location                             16970 non-null  object
 2   total_vaccinations                   16970 non-null  float64
 3   total_vaccinations_per_hundred       16970 non-null  float64
 4   total_distributed                    16970 non-null  float64
 5   distributed_per_hundred              16970 non-null  float64
 6   people_vaccinated                    16970 non-null  float64
 7   people_vaccinated_per_hundred        16970 non-null  float64
 8   people_fully_vaccinated              16970 non-null  float64
 9   people_fully_vaccinated_per_hundred  16970 non-null  float64
 10  daily_vaccinations                   16970 non-null  float64
 11  daily_vaccinations_per_million       16970 non-null  float64
 12  total_boosters                       16970 non-null  float64
 13  total_boosters_per_hundred           16970 non-null  float64
dtypes: float64(12), object(2)
memory usage: 1.9+ MB

In [56]:
data_df['date'] = pd.to_datetime(data_df['date'])

In [57]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16970 entries, 263 to 52387
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   date                                 16970 non-null  datetime64[ns]
 1   location                             16970 non-null  object
 2   total_vaccinations                   16970 non-null  float64
 3   total_vaccinations_per_hundred       16970 non-null  float64
 4   total_distributed                    16970 non-null  float64
 5   distributed_per_hundred              16970 non-null  float64
 6   people_vaccinated                    16970 non-null  float64
 7   people_vaccinated_per_hundred        16970 non-null  float64
 8   people_fully_vaccinated              16970 non-null  float64
 9   people_fully_vaccinated_per_hundred  16970 non-null  float64
 10  daily_vaccinations                   16970 non-null  float64
 11  daily_vaccinations_per_million       16970 non-null  float64
 12  total_boosters                       16970 non-null  float64
 13  total_boosters_per_hundred           16970 non-null  float64
dtypes: datetime64[ns](1), float64(12), object(1)
memory usage: 1.9+ MB

In [58]:
year = 2022
new_df_year = data_df[data_df['date'].dt.year == year]
new_df_year

,date,location,total_vaccinations,total_vaccinations_per_hundred,total_distributed,distributed_per_hundred,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,daily_vaccinations_per_million,total_boosters,total_boosters_per_hundred
357,2022-01-04,Alabama,5678299.00,115.81,8027420.00,163.72,2884819.00,58.84,2345599.00,47.84,10478.00,2137.00,603124.00,12.30
358,2022-01-05,Alabama,5681793.00,115.88,8071240.00,164.61,2886070.00,58.86,2346404.00,47.85,10508.00,2143.00,604626.00,12.33
359,2022-01-06,Alabama,5695747.00,116.16,8391130.00,171.14,2890246.00,58.95,2349085.00,47.91,10216.00,2084.00,611874.00,12.48
360,2022-01-07,Alabama,5710373.00,116.46,8391130.00,171.14,2894430.00,59.03,2351731.00,47.96,10761.00,2195.00,619829.00,12.64
361,2022-01-08,Alabama,5723382.00,116.73,8498480.00,173.33,2898115.00,59.11,2354087.00,48.01,11075.00,2259.00,627028.00,12.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52261,2022-11-30,Wyoming,835616.00,144.38,1224385.00,211.55,350112.00,60.49,305397.00,52.77,279.00,482.00,207094.00,35.78
52268,2022-12-07,Wyoming,836023.00,144.45,1231985.00,212.87,350354.00,60.54,305543.00,52.79,58.00,100.00,207113.00,35.79
52275,2022-12-14,Wyoming,836281.00,144.50,1234765.00,213.35,350512.00,60.56,305642.00,52.81,37.00,64.00,207114.00,35.79
52282,2022-12-21,Wyoming,843727.00,145.78,1240065.00,214.26,351292.00,60.70,306174.00,52.90,1064.00,1838.00,213248.00,36.85
52289,2022-12-28,Wyoming,844861.00,145.98,1241825.00,214.57,351498.00,60.73,306301.00,52.92,162.00,280.00,214049.00,36.98

In [59]:
new_df_year.fillna(0, inplace=True)

C:\Users\juhis\AppData\Local\Temp\ipykernel_9620\272596926.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_year.fillna(0, inplace=True)

In [60]:
new_df_year['location'].unique()

array(['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Federated States of Micronesia',
       'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois',
       'Indian Health Svc', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Marshall Islands', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York State', 'North Carolina',
       'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Republic of Palau',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'United States', 'Utah', 'Vermont', 'Virgin Islands',
       'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

In [79]:
# drop locations that are not states

drop_locations = ['Marshall Islands','Indian Health Svc','United States','American Samoa','District of Columbia','Federated States of Micronesia','Northern Mariana Islands',
            'Virgin Islands','Republic of Palau','Puerto Rico','Guam']
new_df_year.drop(new_df_year[new_df_year['location'].isin(drop_locations)].index, inplace=True)
new_df_year.shape

C:\Users\juhis\AppData\Local\Temp\ipykernel_9620\2478634854.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df_year.drop(new_df_year[new_df_year['location'].isin(drop_locations)].index, inplace=True)

(8157, 14)

In [80]:
location_df= new_df_year['location'].unique()
location_df

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York State', 'North Carolina', 'North Dakota', 'Ohio',
       'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin',
       'Wyoming'], dtype=object)

In [81]:
new_data_df_grouped = new_df_year.groupby(['location']).sum().reset_index()

In [84]:
pd.options.display.float_format = '{:.2f}'.format

In [85]:
new_data_df_grouped.head()

,location,total_vaccinations,total_vaccinations_per_hundred,total_distributed,distributed_per_hundred,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,daily_vaccinations_per_million,total_boosters,total_boosters_per_hundred
0,Alabama,1112502265.00,22689.35,1722428570.00,35128.81,546742178.00,11150.76,444736421.00,9070.42,773953.00,157841.00,150473306.00,3068.85
1,Alaska,167993052.00,22964.09,228747645.00,31269.16,75416102.00,10309.19,66817104.00,9133.77,130727.00,178700.00,31870764.00,4356.62
2,Arizona,2115124661.00,29059.03,2606561140.00,35810.74,932195443.00,12807.12,785151488.00,10786.90,2021814.00,277772.00,456338648.00,6269.52
3,Arkansas,755842625.00,25046.07,1108293000.00,36725.08,360283171.00,11938.60,293552144.00,9727.33,553975.00,183564.00,122271314.00,4051.69
4,California,6478700142.00,16396.68,7887011845.00,19960.91,2823560645.00,7146.08,2456102099.00,6216.06,5670847.00,143520.00,1379825635.00,3492.17

In [78]:
new_data_df_grouped.to_csv("data/Covid_vaccination.csv", header=True)