In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
data = pd.read_csv("C:/Users/juhis/Downloads/us_state_vaccinations.csv")

In [3]:
data.head()

,date,location,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used,total_boosters,total_boosters_per_hundred
0,2021-01-12,Alabama,78134.0,377025.0,70861.0,0.15,1.59,7270.0,1.45,7.69,NaN,NaN,NaN,0.207,NaN,NaN
1,2021-01-13,Alabama,84040.0,378975.0,74792.0,0.19,1.71,9245.0,1.53,7.73,5906.0,5906.0,1205.0,0.222,NaN,NaN
2,2021-01-14,Alabama,92300.0,435350.0,80480.0,NaN,1.88,NaN,1.64,8.88,8260.0,7083.0,1445.0,0.212,NaN,NaN
3,2021-01-15,Alabama,100567.0,444650.0,86956.0,0.28,2.05,13488.0,1.77,9.07,8267.0,7478.0,1525.0,0.226,NaN,NaN
4,2021-01-16,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7498.0,1529.0,NaN,NaN,NaN

In [4]:
data.dropna()

,date,location,total_vaccinations,total_distributed,people_vaccinated,people_fully_vaccinated_per_hundred,total_vaccinations_per_hundred,people_fully_vaccinated,people_vaccinated_per_hundred,distributed_per_hundred,daily_vaccinations_raw,daily_vaccinations,daily_vaccinations_per_million,share_doses_used,total_boosters,total_boosters_per_hundred
263,2021-10-02,Alabama,4544355.0,6738280.0,2586950.0,42.73,92.68,2094920.0,52.76,137.43,9583.0,10431.0,2127.0,0.674,2985.0,0.06
264,2021-10-03,Alabama,4565230.0,6736650.0,2592096.0,42.89,93.11,2103203.0,52.87,137.39,20875.0,11389.0,2323.0,0.678,10683.0,0.22
265,2021-10-04,Alabama,4579477.0,6736230.0,2595947.0,43.02,93.40,2109349.0,52.94,137.38,14247.0,12178.0,2484.0,0.680,14974.0,0.31
266,2021-10-05,Alabama,4584378.0,6742810.0,2597448.0,43.07,93.50,2111925.0,52.97,137.52,4901.0,10470.0,2135.0,0.680,15821.0,0.32
267,2021-10-06,Alabama,4594736.0,6757960.0,2600070.0,43.15,93.71,2115732.0,53.03,137.83,10358.0,11500.0,2345.0,0.680,19856.0,0.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52090,2022-06-12,Wyoming,758185.0,1014285.0,338217.0,51.23,131.00,296500.0,58.44,175.25,45.0,325.0,562.0,0.748,150227.0,25.96
52091,2022-06-13,Wyoming,758188.0,1014285.0,338220.0,51.23,131.00,296500.0,58.44,175.25,3.0,325.0,562.0,0.748,150227.0,25.96
52092,2022-06-14,Wyoming,758784.0,1015885.0,338314.0,51.24,131.11,296557.0,58.46,175.53,596.0,307.0,530.0,0.747,150679.0,26.03
52093,2022-06-15,Wyoming,759047.0,1015985.0,338384.0,51.25,131.15,296603.0,58.47,175.55,263.0,307.0,530.0,0.747,150830.0,26.06
52094,2022-06-16,Wyoming,759520.0,1016985.0,338492.0,51.26,131.23,296656.0,58.49,175.72,473.0,313.0,541.0,0.747,151146.0,26.12

In [5]:
data_df = data[['date','location','total_vaccinations','total_vaccinations_per_hundred','total_distributed',
                'distributed_per_hundred','people_vaccinated', 'people_vaccinated_per_hundred','people_fully_vaccinated',
                'people_fully_vaccinated_per_hundred','daily_vaccinations','daily_vaccinations_per_million',
                'total_boosters','total_boosters_per_hundred']].dropna()
data_df

,date,location,total_vaccinations,total_vaccinations_per_hundred,total_distributed,distributed_per_hundred,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,daily_vaccinations_per_million,total_boosters,total_boosters_per_hundred
263,2021-10-02,Alabama,4544355.0,92.68,6738280.0,137.43,2586950.0,52.76,2094920.0,42.73,10431.0,2127.0,2985.0,0.06
264,2021-10-03,Alabama,4565230.0,93.11,6736650.0,137.39,2592096.0,52.87,2103203.0,42.89,11389.0,2323.0,10683.0,0.22
265,2021-10-04,Alabama,4579477.0,93.40,6736230.0,137.38,2595947.0,52.94,2109349.0,43.02,12178.0,2484.0,14974.0,0.31
266,2021-10-05,Alabama,4584378.0,93.50,6742810.0,137.52,2597448.0,52.97,2111925.0,43.07,10470.0,2135.0,15821.0,0.32
267,2021-10-06,Alabama,4594736.0,93.71,6757960.0,137.83,2600070.0,53.03,2115732.0,43.15,11500.0,2345.0,19856.0,0.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52359,2023-03-08,Wyoming,850076.0,146.88,1264795.0,218.54,352806.0,60.96,307019.0,53.05,67.0,116.0,217238.0,37.54
52366,2023-03-15,Wyoming,850626.0,146.97,1267395.0,218.98,352934.0,60.98,307130.0,53.07,79.0,136.0,217549.0,37.59
52373,2023-03-22,Wyoming,851096.0,147.06,1269455.0,219.34,353073.0,61.01,307218.0,53.08,67.0,116.0,217792.0,37.63
52380,2023-03-29,Wyoming,851551.0,147.13,1272055.0,219.79,353200.0,61.03,307293.0,53.10,65.0,112.0,218045.0,37.67
52387,2023-04-05,Wyoming,851602.0,147.14,1273165.0,219.98,353233.0,61.03,307311.0,53.10,7.0,12.0,218045.0,37.67

In [6]:
data_df.head()

,date,location,total_vaccinations,total_vaccinations_per_hundred,total_distributed,distributed_per_hundred,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,daily_vaccinations_per_million,total_boosters,total_boosters_per_hundred
263,2021-10-02,Alabama,4544355.0,92.68,6738280.0,137.43,2586950.0,52.76,2094920.0,42.73,10431.0,2127.0,2985.0,0.06
264,2021-10-03,Alabama,4565230.0,93.11,6736650.0,137.39,2592096.0,52.87,2103203.0,42.89,11389.0,2323.0,10683.0,0.22
265,2021-10-04,Alabama,4579477.0,93.40,6736230.0,137.38,2595947.0,52.94,2109349.0,43.02,12178.0,2484.0,14974.0,0.31
266,2021-10-05,Alabama,4584378.0,93.50,6742810.0,137.52,2597448.0,52.97,2111925.0,43.07,10470.0,2135.0,15821.0,0.32
267,2021-10-06,Alabama,4594736.0,93.71,6757960.0,137.83,2600070.0,53.03,2115732.0,43.15,11500.0,2345.0,19856.0,0.40

In [7]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16970 entries, 263 to 52387
Data columns (total 14 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   date                                 16970 non-null  object
 1   location                             16970 non-null  object
 2   total_vaccinations                   16970 non-null  float64
 3   total_vaccinations_per_hundred       16970 non-null  float64
 4   total_distributed                    16970 non-null  float64
 5   distributed_per_hundred              16970 non-null  float64
 6   people_vaccinated                    16970 non-null  float64
 7   people_vaccinated_per_hundred        16970 non-null  float64
 8   people_fully_vaccinated              16970 non-null  float64
 9   people_fully_vaccinated_per_hundred  16970 non-null  float64
 10  daily_vaccinations                   16970 non-null  float64
 11  daily_vaccinations_per_million       16970 non-null  float64
 12  total_boosters                       16970 non-null  float64
 13  total_boosters_per_hundred           16970 non-null  float64
dtypes: float64(12), object(2)
memory usage: 1.9+ MB

In [8]:
data_df.fillna(0, inplace=True)

In [9]:
data_df['location'].unique()

array(['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Federated States of Micronesia',
       'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois',
       'Indian Health Svc', 'Indiana', 'Iowa', 'Kansas', 'Kentucky',
       'Louisiana', 'Maine', 'Marshall Islands', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York State', 'North Carolina',
       'North Dakota', 'Northern Mariana Islands', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Republic of Palau',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'United States', 'Utah', 'Vermont', 'Virgin Islands',
       'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'],
      dtype=object)

In [10]:
# drop locations that are not states

drop_locations = ['Marshall Islands','Indian Health Svc','United States']
data_df.drop(data_df[data_df['location'].isin(drop_locations)].index, inplace=True)
data_df.shape

(16097, 14)

In [11]:
data_df['location'].unique()

array(['Alabama', 'Alaska', 'American Samoa', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Federated States of Micronesia',
       'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois',
       'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine',
       'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York State',
       'North Carolina', 'North Dakota', 'Northern Mariana Islands',
       'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Puerto Rico',
       'Republic of Palau', 'Rhode Island', 'South Carolina',
       'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
       'Virgin Islands', 'Virginia', 'Washington', 'West Virginia',
       'Wisconsin', 'Wyoming'], dtype=object)