In [13]:
# Pandas
import pandas as pd
from sqlite3 import connect

# SQL Alchemy
from sqlalchemy import create_engine
import psycopg2

In [14]:
# declare the connection string specifying
# the host name database name use name
# and password
conn_string = "host='localhost' dbname='covid_vaccines'\
user='postgres' password='Juhi@123'"
 
# use connect function to establish the connection
conn = psycopg2.connect(conn_string)

In [28]:
# Query All Records in the the Database
data = pd.read_sql('select * from vaccine', conn)

c:\Users\juhis\anaconda3\New folder\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [29]:
# Preview the Data
data.head()

,id,date,location,total_vaccinations,total_vaccinations_per_hundred,total_distributed,distributed_per_hundred,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,daily_vaccinations_per_million,total_boosters,total_boosters_per_hundred
0,263,2021-10-02,Alabama,4544355.0,92.68,6738280.0,137.43,2586950.0,52.76,2094920.0,42.73,10431.0,2127.0,2985.0,0.06
1,264,2021-10-03,Alabama,4565230.0,93.11,6736650.0,137.39,2592096.0,52.87,2103203.0,42.89,11389.0,2323.0,10683.0,0.22
2,265,2021-10-04,Alabama,4579477.0,93.40,6736230.0,137.38,2595947.0,52.94,2109349.0,43.02,12178.0,2484.0,14974.0,0.31
3,266,2021-10-05,Alabama,4584378.0,93.50,6742810.0,137.52,2597448.0,52.97,2111925.0,43.07,10470.0,2135.0,15821.0,0.32
4,267,2021-10-06,Alabama,4594736.0,93.71,6757960.0,137.83,2600070.0,53.03,2115732.0,43.15,11500.0,2345.0,19856.0,0.40