In [1]:
# Pandas
import pandas as pd
from sqlite3 import connect

# SQL Alchemy
from sqlalchemy import create_engine
import psycopg2

In [2]:
# declare the connection string specifying
# the host name database name use name
# and password
conn_string = "host='localhost' dbname='covid_vaccine'\
user='postgres' password='Juhi@123'"
 
# use connect function to establish the connection
conn = psycopg2.connect(conn_string)

In [3]:
# Query All Records in the the Database
data = pd.read_sql('select * from vaccine2', conn)

c:\Users\juhis\anaconda3\New folder\lib\site-packages\pandas\io\sql.py:762: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [4]:
# Preview the Data
data.head()

,id,date,location,total_vaccinations,total_vaccinations_per_hundred,total_distributed,distributed_per_hundred,people_vaccinated,people_vaccinated_per_hundred,people_fully_vaccinated,people_fully_vaccinated_per_hundred,daily_vaccinations,daily_vaccinations_per_million,total_boosters,total_boosters_per_hundred,location_,latitude,longitude
0,715,2022-12-28,Alabama,6929554.0,141.33,11897230.0,242.64,3178492.0,64.83,2599499.0,53.02,1479.0,302.0,1319456.0,26.91,Alabama,32.377716,-86.300568
1,1529,2022-12-28,Alaska,1303955.0,178.25,2066295.0,282.46,532210.0,72.75,475125.0,64.95,332.0,454.0,338839.0,46.32,Alaska,58.301598,-134.420212
2,3157,2022-12-28,Arizona,14302488.0,196.50,19039550.0,261.58,5610927.0,77.09,4788266.0,65.78,3551.0,488.0,4242480.0,58.29,Arizona,33.448143,-112.096962
3,3971,2022-12-28,Arkansas,4803994.0,159.19,8034900.0,266.25,2101193.0,69.63,1710670.0,56.69,1046.0,347.0,1107336.0,36.69,Arkansas,34.746613,-92.288986
4,5599,2022-12-28,California,86604013.0,219.18,115820215.0,293.13,33317358.0,84.32,29388863.0,74.38,79661.0,2016.0,25997328.0,65.80,California,38.576668,-121.493629